### ISSUE TITLE
Cohesion calculation bug

### ISSUE THREAD

**Issue by bezo97** [anuraghazra/EvolutionAquerium#1]
Hey, i've looked at the flocking algorithm to see how it works. There seems to be a bug in the line below:
https://github.com/anuraghazra/EvolutionAquerium/blob/3d4f599d7de03ed9c28d19d17787a3a7f7ed3255/src/js/agent.js#L167
The cohesion force is mistakenly calculated with the align() function instead of cohesion().

**Comment by anuraghazra** [comment]
thank you very much...
